djangp/urls.py
from django.conf.urls import url
from django.contrib import admin
from todo.views import get_todo_list, create_an_item, edit_an_item, toggle_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', get_todo_list),
    url(r'^add$', create_an_item),
    url(r'^edit/(?P<id>\d+)$', edit_an_item),
    url(r'^toggle/(?P<id>\d+)$', toggle_status)

]

todo/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=30, blank=False)
    done = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'done')

todo/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Item
from .forms import ItemForm

# Create your views here.
def get_todo_list(request):
    results = Item.objects.all()
    return render(request, "todo_list.html", {'items': results})

def create_an_item(request):
    if request.method=="POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect (get_todo_list)
    
    else:
        form = ItemForm()
        
    return render(request, "item_form.html", {'form': form})

    #     new_item = Item()
    #     new_item.name = request.POST.get('name')
    #     new_item.done = 'done' in request.POST
    #     new_item.save()
    #     return redirect (get_todo_list)

    # return render(request, "item_form.html")

def edit_an_item(request, id):
    item = get_object_or_404(Item, pk=id)

    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect(get_todo_list)

    else:
        form = ItemForm(instance=item)    

    return render(request, "item_form.html", {'form': form})

def toggle_status(request, id):
    item = get_object_or_404(Item, pk=id)
    item.done = not item.done
    item.save()
    return redirect(get_todo_list)        

todo/templates/item_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo Form</title>
</head>
<body>
    <h1>I need to do this...</h1>

    <form action="" method="POST">

        {% csrf_token %}
        
        {{ form.as_p }}

        <!-- <label for="id_name">Name:</label><br>
        <input type="text" id="id_name" name="name"><br>
        <br>
        <label for="id_done">Done:</label><br>
        <input type="checkbox" id="id_done" name="done"><br> 
        <br>-->
        <button type="submit">Save</button>

    </form>
</body>
</html>

todo/templates/todo_list.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Todo List</title>
</head>

<body>
	<h1>Things I need to do...</h1>
	<table>
        {% for item in items %}
            <tr>
                {% if item.done%}
                    <td>
                    <strike>{{ item.name }}</strike>
                    </td>
                {% else %}
                    <td>
                    {{ item.name }}
                    </td> 
                {% endif %}
                <td>
                    <form method="POST" action="toggle/{{item.id}}">{% csrf_token %}<input type="submit" value="Toggle"></form>
                </td>
                <td>
                    <form method="GET" action="edit/{{item.id}}"><input type="submit" value="Edit"></form>
                </td>
            </tr>
        {% empty %}
            <p>You have nothing to do.</p>
        {% endfor %}
	</table>

    <a href="add">Add an Item</a>

</body>

</html>